connection:
  protocol: http
  endpoint: localstack
  port: 4566

resources:
  my-bucket:
    type: s3
    options:
      name: bucket
  my-queue:
    type: sqs
    options:
      name: queue-name
      dead_letter: true
