connection:
  protocol: http
  endpoint: localstack
  port: 4566
  region: us-east-1 #localstack default

resources:
  my-bucket:
    type: s3
    restart: true
    options:
      name: my-bucket
  my-queue:
    type: sqs
    options:
      name: my-queue
      messageRetentionPeriod: "345600" # 4 days (seconds)
      visibilityTimeout: "30" # 30 seconds
