connection:
  protocol: http
  endpoint: localhost
  port: 4566

resources:
  my-bucket:
    type: s3
    restart: true
    options:
      name: my-bucket
#  my-queue:
#    type: sqs
#    options:
#      name: my-queue
#      dead_letter: true
