connection:
  protocol: http
  endpoint: localstack
  port: 4566

resources:
  my-bucket:
    type: s3
    options:
      name: my-bucket
  my-queue:
    type: sqs
    options:
      name: my-queue
      dead_letter: true
